heartbeat:
  delay: 10
  time-unit: SECONDS

pekko:
  remote:
    artery:
      canonical:
        hostname: "127.0.0.1"
        port: "2551"
  cluster:
    seed-nodes:
      - "pekko://WsServerClusterSystem@${pekko.remote.artery.canonical.hostname}:${pekko.remote.artery.canonical.port}"
