spring:
  application:
    name: dungeon-walker-gateway-server
  profiles:
    active: ${APP_PROFILE:dev}
  config:
    import: "${CONFIG_SERVER_URL:optional:configserver:http://localhost:8083/}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials
            strategy: RETAIN_FIRST

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted # Enable gateway-related endpoints inside the actuator
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true # Enable the environment info endpoint.
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"