spring:
  application:
    name: dungeon-walker-gateway-server
  profiles:
    active: ${APP_PROFILE:dev}
  config:
    import: "${CONFIG_SERVER_URL:optional:configserver:http://localhost:8083/}"
  cloud:
    gateway:
      server:
        webflux:            # 1. Cloud Gateway WebFlux Server
          discovery:        # 2. Connect to the gateway server
            locator:        # 3. locate the gateway routes of other services
              enabled: true # 4. Use the same to forward the traffic from external clients
              lower-case-service-id: true # 5. Converted service ID to lowercase
