server:
  port: 8085

info: # The data to be displayed in the info endpoint.
  app:
    name: "dungeon-walker-gateway-server"
    description: "Dungeon Walker Gateway Server (STG)"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted # Enable gateway-related endpoints inside the actuator
  info:
    env:
      enabled: true # Enable the environment info endpoint.

eureka:
  instance:
    preferIpAddress: false
  client:
    fetchRegistry: true # enable to fetch registry details of other microservices
    registerWithEureka: true # self-register to the Eureka server
    serviceUrl:
      defaultZone: http://dungeon-walker-discovery-server:8084/eureka/

logging:
  level:
    root: info
    momomomo:
      dungeonwalker:
        gateway: debug
