# - - STARTUP - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

server:
  port: 8080

info: # The data to be displayed in the info endpoint.
  app:
    name: "dungeon-walker-ws-server"
    description: "Dungeon Walker WebSocket Server (DEV)"

logging:
  level:
    root: info
    org:
      apache:
        kafka: warn
    momomomo:
      dungeonwalker:
        wsserver:
          startup: debug
          transport: debug
          core: debug
          domain: debug

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true # enable to fetch registry details of other microservices
    registerWithEureka: true # self-register to the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

# - - TRANSPORT - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

spring:
  kafka:
    consumer:
      enable-auto-commit: false
      bootstrap-servers: localhost:9092
      concurrency: 3
      poll-timeout: 3000
    producer:
      bootstrap-servers: localhost:9092
      acks: 1
      retries: 3

kafka:
  topic:
    game-engine:
      inbound: "game-engine-producer-topic"
      outbound: "game-engine-consumer-topic"

# - - CORE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

heartbeat:
  delay: 10
  time-unit: SECONDS

pekko:
  remote:
    artery:
      canonical:
        hostname: "127.0.0.1"
        port: "2551"
  cluster:
    seed-nodes:
      - "pekko://WsServerClusterSystem@127.0.0.1:2551"
