# - - STARTUP - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

server:
  port: 8086

info: # The data to be displayed in the info endpoint.
  app:
    name: "dungeon-walker-history"
    description: "Dungeon Walker History (DEV)"

logging:
  level:
    root: info
    momomomo:
      dungeonwalker:
        history:
          startup: debug
          transport: debug
          core: debug
          domain: debug

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true # enable to fetch registry details of other microservices
    registerWithEureka: true # self-register to the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

# - - TRANSPORT - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

# - - CORE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# TBD