# - - STARTUP - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

server:
  port: 8081

info: # The data to be displayed in the info endpoint.
  app:
    name: "dungeon-walker-engine"
    description: "Dungeon Walker Engine (STG)"

logging:
  level:
    root: info
    org:
      apache:
        kafka: warn
    momomomo:
      dungeonwalker:
        engine:
          startup: debug
          transport: debug
          core: debug
          domain: debug

eureka:
  instance:
    preferIpAddress: false
  client:
    fetchRegistry: true # enable to fetch registry details of other microservices
    registerWithEureka: true # self-register to the Eureka server
    serviceUrl:
      defaultZone: http://dungeon-walker-discovery-server:8084/eureka/

# - - TRANSPORT - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

spring:
  kafka:
    consumer:
      enable-auto-commit: false
      bootstrap-servers: kafka:29092
      concurrency: 3
      poll-timeout: 3000
    producer:
      bootstrap-servers: kafka:29092
      acks: 1
      retries: 3

kafka:
  topic:
    game-engine:
      inbound: "game-engine-consumer-topic"
      outbound: "game-engine-producer-topic"

# - - APPLICATION - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

pekko:
  persistence:
    r2dbc:
      dialect: "postgres"
      connection-factory:
        driver: "postgres"
        host: "postgres-db"
        port: "5432"
        database: "postgres"
        user: "postgres"
        password: "postgres"
  remote:
    artery:
      canonical:
        hostname: "127.0.0.1"
        port: "2552"
  cluster:
    seed-nodes:
      - "pekko://EngineClusterSystem@127.0.0.1:2552"

