services:

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # - - - - KAFKA - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  kafka:
    extends:
      file: docker-compose-infra.yml
      service: kafka
    networks:
      - dungeon-walker-network

  # - - - - POSTGRES - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # After starting the container for the first time (with no volume), in the "dungeon-walker-docker" folder, run:
  # docker exec -i postgres-db psql -U postgres -t < ddl-scripts/create_tables_postgres.sql
  
  postgres-db:
    extends:
      file: docker-compose-infra.yml
      service: postgres-db
    healthcheck:
      test: [ 'CMD', 'pg_isready', "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - dungeon-walker-network

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # - - - - LOKI - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  grafana-loki-read:
    extends:
      file: docker-compose-grafana.yml
      service: grafana-loki-read
    depends_on:
      - grafana-minio
    networks:
      - dungeon-walker-network

  grafana-loki-write:
    extends:
      file: docker-compose-grafana.yml
      service: grafana-loki-write
    depends_on:
      - grafana-minio
    networks:
      - dungeon-walker-network

  grafana-loki-backend:
    extends:
      file: docker-compose-grafana.yml
      service: grafana-loki-backend
    depends_on:
      - grafana-minio
    networks:
      - dungeon-walker-network

  # - - - - ALLOY - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  grafana-alloy:
    extends:
      file: docker-compose-grafana.yml
      service: grafana-alloy
    depends_on:
      - grafana-nginx-gateway
    networks:
      - dungeon-walker-network

  # - - - - GRAFANA - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  grafana:
    extends:
      file: docker-compose-grafana.yml
      service: grafana
    depends_on:
      - grafana-nginx-gateway
    networks:
      - dungeon-walker-network

  # - - - - NGINX - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  grafana-nginx-gateway:
    extends:
      file: docker-compose-grafana.yml
      service: grafana-nginx-gateway
    depends_on:
      - grafana-loki-read
      - grafana-loki-write
    networks:
      - dungeon-walker-network

  # - - - - MINIO (S3-like) - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  grafana-minio:
    extends:
      file: docker-compose-grafana.yml
      service: grafana-minio
    networks:
      - dungeon-walker-network

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # - - - - CONFIG SERVER - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # To create this container's image, go to the folder where this project is located and run:
  # mvn clean install jib:dockerBuild -DskipTests

  dungeon-walker-config-server:
    image: alejoceballos/dungeon-walker-config-server:v1
    container_name: dungeon-walker-config-server
    ports:
      - "8083:8083"
    healthcheck:
      test: "curl --fail --silent http://localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - dungeon-walker-network
    depends_on:
      - kafka
      - postgres-db

  # - - - - DISCOVERY SERVER - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # To create this container's image, go to the folder where this project is located and run:
  # mvn clean install jib:dockerBuild -DskipTests

  dungeon-walker-discovery-server:
    image: alejoceballos/dungeon-walker-discovery-server:v1
    container_name: dungeon-walker-discovery-server
    ports:
      - "8084:8084"
    environment:
      APP_PROFILE: stg
      CONFIG_SERVER_URL: "optional:configserver:http://dungeon-walker-config-server:8083/"
    healthcheck:
      test: "curl --fail --silent http://localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - dungeon-walker-network
    depends_on:
      dungeon-walker-config-server:
        condition: service_healthy

  # - - - - ENGINE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # To create this container's image, go to the folder where this project is located and run:
  # mvn clean install jib:dockerBuild -DskipTests

  dungeon-walker-engine:
    image: alejoceballos/dungeon-walker-engine:v1
    container_name: dungeon-walker-engine
    ports:
      - "8081:8081"
    environment:
      APP_PROFILE: stg
      CONFIG_SERVER_URL: "optional:configserver:http://dungeon-walker-config-server:8083/"
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - dungeon-walker-network
    depends_on:
      dungeon-walker-discovery-server:
        condition: service_healthy

  # - - - - WEBSOCKET SERVER - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # To create this container's image, go to the folder where this project is located and run:
  # mvn clean install jib:dockerBuild -DskipTests

  dungeon-walker-ws-server:
    image: alejoceballos/dungeon-walker-ws-server:v1
    container_name: dungeon-walker-ws-server
    ports:
      - "8080:8080"
    environment:
      APP_PROFILE: stg
      CONFIG_SERVER_URL: "optional:configserver:http://dungeon-walker-config-server:8083/"
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - dungeon-walker-network
    depends_on:
      dungeon-walker-engine:
        condition: service_healthy

  # - - - - GATEWAY SERVER - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # To create this container's image, go to the folder where this project is located and run:
  # mvn clean install jib:dockerBuild -DskipTests

  dungeon-walker-gateway-server:
    image: alejoceballos/dungeon-walker-gateway-server:v1
    container_name: dungeon-walker-gateway-server
    ports:
      - "8085:8085"
    environment:
      APP_PROFILE: stg
      CONFIG_SERVER_URL: "optional:configserver:http://dungeon-walker-config-server:8083/"
    healthcheck:
      test: "curl --fail --silent http://localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - dungeon-walker-network
    depends_on:
      dungeon-walker-ws-server:
        condition: service_healthy

  # - - - - UI - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # To create this container's image, go to the folder where this project is located and run:
  # mvn clean install jib:dockerBuild -DskipTests

  #  dungeon-walker-ui:
  #    image: alejoceballos/dungeon-walker-ui:v1
  #    container_name: dungeon-walker-ui
  #    ports:
  #      - "8082:8082"
  #    networks:
  #      - dungeon-walker-network
  #    depends_on:
  #      dungeon-walker-gateway-server:
  #        condition: service_healthy

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

networks:
  dungeon-walker-network:
    driver: bridge