spring:
  application:
    name: dungeon-walker-ws-server
  profiles:
    active: ${APP_PROFILE:dev}
  config:
    import: "${CONFIG_SERVER_URL:optional:configserver:http://localhost:8083/}"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown: # Enable the shutdown endpoint allowing to gracefully shut down the service
      access: unrestricted # Allow shutdown endpoint to be accessed without authentication.
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
  info:
    env:
      enabled: true # Enable the environment info endpoint.
