pekko {

  actor {
    provider = "cluster"

    serializers {
      jackson-json = "org.apache.pekko.serialization.jackson.JacksonJsonSerializer"
      jackson-cbor = "org.apache.pekko.serialization.jackson.JacksonCborSerializer"
    }

    serialization-bindings {
      "momomomo.dungeonwalker.engine.domain.model.dungeon.state.DungeonState" = jackson-json
      "momomomo.dungeonwalker.engine.domain.model.walker.state.WalkerState" = jackson-json
    }
  }

  persistence {
    state {
      plugin = "pekko.persistence.r2dbc.state"
    }

    journal {
      plugin = "pekko.persistence.r2dbc.journal"
    }

    snapshot-store {
      plugin = "pekko.persistence.r2dbc.snapshot"
    }
  }

  cluster {
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

}