websocket:
  endpoint: /ws-endpoint
  allowed-origin-patterns: "*"

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: momomomo.dungeonwalker.contract.serializer.engine.EngineMessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: momomomo.dungeonwalker.contract.serializer.client.ClientRequestSerializer
