package momomomo.dungeonwalker.wsserver.domain.input.engine;

/**
 * All subclasses of this interface represent a message that must be sent to all logged clients
 * (i.e. broadcasted). These messages are generated by the game engine and are meant to be sent to all clients,
 * regardless of their individual state or actions. They typically contain information about global events
 * or updates in the game that are relevant to all players.
 *
 * @see WalkersPositionsData
 */
public interface BroadcastMessage extends EngineMessageValue {
}
